server:
  port: 8000
  servlet:
    context-path: /

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: alaxhenry@gmail.com
    password: "Tmdcjdahzk12#"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
      url: jdbc:mariadb://localhost:3306/portfolio?serverTimezone=Asia/Seoul
      username: alaxhenry
      password: Tmdcjdahzk12#
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create 이라 하면 테이블을 새로 만들겠다고 하는 것 // 최초에만 create 하고 이후에 update 로 변경해줘야한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity를 만들때 테이블 을 만들때 자바 파일 변수명데로 만들어주겠다는의미
      use-new-id-generator-mappings: false #jpa 의 넘버링 전략을 따르지 않겠다는 의미이다
    #show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false

  #OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 470976221479-6v3rg4shi1n2g3ge768hfpu9urkiddkl.apps.googleusercontent.com
            clientSecret: DTeNR55f6dOB8pJ5oHsg2aRK
            scope:
              - email
              - profile


#절대 노출되면 안되는 비밀번호 (카카오 로그인 하는 사람들 모두 비밀번호 이하로 통일 됨) 이게 노출되는 순간 모든 OAuth가 뚤린다고 보면된다.
cos:
  key: cos1234

