
server:
  port : 8081


spring:
  datasource:
      url: jdbc:mariadb://localhost:3306/portfolio?serverTimezone=Asia/Seoul
      username: alaxhenry
      password: Tmdcjdahzk12#
      driver-class-name: org.mariadb.jdbc.Driver

